### ISSUE TITLE
Keeps getting System.ArgumentException: The payload is not in accepted XML format. The first node should be Badge/Tile/Toast.

### ISSUE THREAD

**Issue by nguyenquyhy** [anbare/NotificationsExtensions#18]
I am using NotificationsExtensions in an Azure WebJob and I keep getting`System.ArgumentException: The payload is not in accepted XML format. The first node should be Badge/Tile/Toast. If want to send raw notification, please set header to wns/raw.` from the Azure Notification Hub SDK. The toast notifications still get delivered as expected though.
Below is a relevant part of the stack trace:

```
   at Microsoft.Azure.NotificationHubs.RegistrationSDKHelper.DetectWindowsTemplateRegistationType(String body, String errorMsg)
   at Microsoft.Azure.NotificationHubs.WindowsNotification.OnValidateAndPopulateHeaders()
   at Microsoft.Azure.NotificationHubs.Notification.ValidateAndPopulateHeaders()
   at Microsoft.Azure.NotificationHubs.NotificationHubManager.BeginSendNotification(Notification notification, NotificationType notificationType, String tagExpression, String deviceHandle, AsyncCallback callback, Object state)
   at Microsoft.Azure.NotificationHubs.NotificationHubManager.<>c__DisplayClass1.<SendNotificationAsync>b__0(AsyncCallback c, Object s)
```

I have also tried a suggestion from this article https://andywigleyblog.azurewebsites.net/?p=91, but there doesn't seem to be any BOM in the XML payload.

**Comment by andrewleader** [comment]
Hmm, maybe it doesn't like the leading `<?xml version="1.0" encoding="utf-8"?>`

I'll experiment with it, thanks for letting us know! If you figure it out, let us know!

**Comment by andrewleader** [comment]
Maybe this is a bug with Azure WebJob... Sending the notifications directly through WNS works fine. I have a feeling Azure WebJob is trying to do something intelligent and verify that the first node is badge/tile/toast, but it's not ignoring the XML declaration node...

**Comment by nguyenquyhy** [comment]
It could be a problem with my computer. The error suddenly stops happening today. Please feel free to close this issue if you cannot reproduce on your side.

**Comment by andrewleader** [comment]
Thanks for the update, let us know if you find any other issues or if it starts happening again!
